cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
]

products/urls.py
from django.urls import path 
from . import views

urlpatterns=[
    path('product/<int:product_id>/', views.product, name="product"),
    path('products/', views.products, name="products"),
    path('cart/', views.cart, name='cart'),
    path('update_item/<int:item_id>/', views.update_item, name='update_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    ]

projet1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('',include('products.urls')),
]   + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

cart/models.py
from django.db import models
from datetime import datetime
# Create your models here.



class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    verbose_name_plural = "Categories"


class Product(models.Model):
    name=models.CharField(max_length=50)
    content=models.TextField()
    price= models.DecimalField(max_digits=8,decimal_places=3)
    image=models.ImageField(upload_to='photos/%y/%m/%d')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    active= models.BooleanField(default=True)
    date_time = models.DateTimeField(default=datetime.now)
    
    def __str__(self):
        return self.name

    class Meta():
        verbose_name ='prodect'

products/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    verbose_name_plural = "Categories"


class Product(models.Model):
    name=models.CharField(max_length=50)
    content=models.TextField()
    price= models.DecimalField(max_digits=8,decimal_places=3)
    image=models.ImageField(upload_to='photos/%y/%m/%d')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    active= models.BooleanField(default=True)
    date_time = models.DateTimeField(default=datetime.now)
    
    def __str__(self):
        return self.name

    class Meta():
        verbose_name ='prodect'


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    def __str__(self):
        return self.user.username
    def calculate_total(self):
        total = 0
        items = self.itempanier_set.all()
        for item in items:
            total += item.product.price * item.quantity
        return total


class ItemPanier(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    def __str__(self):
        return str(self.product.name)
    

class Orders_Confirm(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    

    

cart/views.py
from django.shortcuts import render

# Create your views here.



from django.shortcuts import render, redirect
from .models import Product
from django.contrib.auth.decorators import login_required
from cart.cart import Cart

@login_required(login_url="/users/login")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("home")

@login_required(login_url="/users/login")
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart_detail")


@login_required(login_url="/users/login")
def cart_detail(request):
    return render(request, 'cart/cart_detail.html')

products/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Product, ItemPanier
from .models import Cart,Orders_Confirm




# Create your views here.
def product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    context = {'product': product}

    if request.method == 'POST':
        quantity = request.POST.get('quantity')
        if quantity:
            user = request.user  # Utilisateur associé (à ajuster selon votre modèle d'authentification)

            cart, created = Cart.objects.get_or_create(user=user)
            item_panier = ItemPanier(cart=cart, product=product, quantity=quantity)
            item_panier.save()

            # Afficher un message de confirmation ou rediriger l'utilisateur vers une autre page
            return redirect('cart')

    return render(request, 'products/product.html', context)


def products(request):
    products = Product.objects.all()  
    context = {'prod': products}
    return render(request, 'products/products.html', context)



def cart(request):
    cart = get_object_or_404(Cart, user=request.user)

    if request.method == 'POST' and 'confirm' in request.POST:
        if cart.itempanier_set.exists():
            orders_confirm = Orders_Confirm.objects.create(cart=cart)
            orders_confirm.save()
            cart.itempanier_set.all().delete()
        else:
            # Handle the case when the cart is empty
            return redirect('cart')  # Replace 'empty_cart' with the appropriate URL or view name

    context = {'cart': cart}
    return render(request, 'products/cart.html', context)

def update_item(request, item_id):
    item = get_object_or_404(ItemPanier, id=item_id)
    
    if 'quantity' in request.POST:
        quantity = int(request.POST['quantity'])
        if quantity > 0:
            item.quantity = quantity
            item.save()
        else:
            item.delete()
    
    # Redirect the user back to the cart page or another appropriate page
    return redirect('cart')
       
    
    # Redirect the user back to the cart page or another appropriate page
    return redirect('cart')  # Redirect back to the cart page

def delete_item(request, item_id):
    item = get_object_or_404(ItemPanier, id=item_id)
    
    item.delete()
    return redirect('cart')  # Redirect back to the cart page

templates/products/cart.html
{% extends 'base.html' %}
{% block content %}
  <h1>Cart</h1>
  <h2>Items:</h2>
  <form method="POST" action="{% url 'cart' %}">
    {% csrf_token %}
  <ul>
    {% for item in cart.itempanier_set.all %}
      <li>
        {{ item.product.name }} - Quantity: {{ item.quantity }}
        <form method="post" action="{% url 'update_item' item.id %}">
          {% csrf_token %}
          <input type="number" name="quantity" value="{{ item.quantity }}" min="0">
          <button type="submit" class="btn btn-primary">Update</button>
        </form>
        <form method="post" action="{% url 'delete_item' item.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </li>
    {% empty %}
      <li>Your cart is empty.</li>
    {% endfor %}
  </ul>

  <p>Total: {{ cart.calculate_total }}</p> 
  <button type="submit" class="btn btn-success" style="background-color: green;" name="confirm">Confirm</button>
</form>
{% endblock %}

templates/products/product.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/product.css' %}">
{% block content %}
<div class="container">
    <div class="row mb-5 mt-5">
        <div class="col-12">
            <div class="text-center">
                <h1 class="fs-5 fw-bold">Product Page</h1>
            </div>
        </div>
    </div>
    <div>
        <div>
            <div style="width: 18rem;">
                <img src="{{ product.image.url }}" alt="Product Image" style="width: 150%;">
                <div>
                    <h5>{{ product.name }}</h5>
                    <p>{{ product.price }} Dh</p>
                    <p>{{ product.content }}</p>
                    <form method="POST" action="{% url 'product' product.id %}">
                        {% csrf_token %}
                        <label for="id_quantity">Quantity:</label>
                        <input type="number" name="quantity" id="id_quantity" value="1" min="1">
                        <button type="submit" class="btn btn-success" style="background-color: green;" name="add_to_cart">Add to Cart</button>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/products/products.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/products.css' %}">
{% block content %}
<div class="container">
    <div class="row mb-5 mt-5">
        <div class="col-12">
            <div class="text-center fs-5 fw-bold">Shop Page</div>
        </div>
    </div>
    <div class="row">
        {% for x in prod %}
        <div class="col-12 col-lg-4 col-md-6 d-flex align-items-center justify-content-center">
            <div class="card " style="width: 18rem;">
                <img src="{{x.image.url}}" class="card-img-top" alt="..."  style="object-fit: cover;width: 100%;height: 200px;">
                <div class="card-body">
                  <h5 class="card-title">{{x.name}}</h5>
                  <p>{{x.price}} <span>Dh</span></p>
                  <a href="{% url 'product' x.id %}" class="btn btn-success" style="background-color: green;">Shop Now</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
    
{% endblock %}